name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t drapp:latest .  # Customize your Docker build command
        docker tag drapp:latest ${{ secrets.DOCKER_USERNAME }}/drapp:latest  # Replace 'myapp' with your image name
        docker push ${{ secrets.DOCKER_USERNAME }}/drapp:latest  # Push the image to Docker Hub
