name: Build, Test, and Push to Docker Hub

on:
  push:
    branches:
      - main  # Adjust to match your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: |
        docker build -t drapp:latest .  # Customize your Docker build command


    - name: Run tests
      run: |
        docker run --name my_test_container myapp:test npm test  # Adjust this command to run your tests

    - name: Push Docker image to Docker Hub
      if: success()  # This ensures the image is only pushed if tests pass
      run: |
        docker tag drapp:latest ${{ secrets.DOCKER_USERNAME }}/drapp:latest  # Replace 'myapp' with your image name
        docker push ${{ secrets.DOCKER_USERNAME }}/drapp:latest  # Push the image to Docker Hub
